import { FaRobot, FaArrowUp } from "react-icons/fa";

const AIRiskScore = () => {
  return (
    <div className="bg-white rounded-2xl shadow-xl p-6">

      <div className="flex justify-between items-center">

        <div>
          <h2 className="text-xl font-bold">
            AI Risk Score
          </h2>

          <p className="text-gray-500">
            Generated by SentinelX AI Engine
          </p>
        </div>

        <FaRobot
          size={40}
          className="text-cyan-600"
        />

      </div>

      <div className="mt-8 flex justify-center">

        <div className="w-40 h-40 rounded-full border-[14px] border-red-500 flex items-center justify-center">

          <div className="text-center">

            <h1 className="text-5xl font-bold">
              91
            </h1>

            <p className="text-gray-500">
              High Risk
            </p>

          </div>

        </div>

      </div>

      <div className="mt-8">

        <div className="flex justify-between mb-2">
          <span>Privilege Misuse</span>
          <span>95%</span>
        </div>

        <div className="w-full bg-gray-200 rounded-full h-3">
          <div className="bg-red-500 h-3 rounded-full w-[95%]"></div>
        </div>

        <div className="flex justify-between mt-5 mb-2">
          <span>Data Exfiltration</span>
          <span>74%</span>
        </div>

        <div className="w-full bg-gray-200 rounded-full h-3">
          <div className="bg-yellow-500 h-3 rounded-full w-[74%]"></div>
        </div>

        <div className="flex justify-between mt-5 mb-2">
          <span>Anomalous Login</span>
          <span>62%</span>
        </div>

        <div className="w-full bg-gray-200 rounded-full h-3">
          <div className="bg-cyan-500 h-3 rounded-full w-[62%]"></div>
        </div>

      </div>

      <div className="mt-8 flex items-center gap-2 text-red-500">

        <FaArrowUp />

        <span className="font-semibold">
          Risk increased by 12% today
        </span>

      </div>

    </div>
  );
};

export default AIRiskScore;